insert into film (film_id, title, director, country, film_language, age_rating, duration) values (1, 'Welcome to Collinwood', 'Antone McTrustram', 'BR', 'Spanish', 13, 173);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (2, 'Treed Murray', 'Tandy McCorkindale', 'ID', 'Khmer', 8, 122);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (3, 'British Sounds', 'Les Cayette', 'CN', 'Romanian', 6, 179);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (4, 'Twilight Saga: Breaking Dawn - Part 1, The', 'Christie McElvogue', 'AR', 'Kyrgyz', 8, 178);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (5, 'End of Days', 'Linnell Preston', 'CN', 'Swedish', 13, 92);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (6, 'Crawlspace', 'Andra Breazeall', 'RU', 'Icelandic', 13, 140);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (7, 'Jodhaa Akbar', 'Corbie Vizard', 'SE', 'Kyrgyz', 18, 159);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (8, 'Something Wild', 'Shelden Thunder', 'TH', 'Portuguese', 14, 80);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (9, 'Everest', 'Dionis Slowan', 'ES', 'Papiamento', 15, 175);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (10, 'Cloudy with a Chance of Meatballs', 'Brenn Harden', 'RU', 'Polish', 15, 103);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (11, 'My Life in Pink (Ma vie en rose)', 'Karla Edworthie', 'GU', 'Belarusian', 17, 94);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (12, 'A.I. Artificial Intelligence', 'Doris Zavittieri', 'UA', 'Afrikaans', 13, 147);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (13, 'Jar City (Mýrin)', 'Margi Itzakovitz', 'NG', 'Malayalam', 14, 82);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (14, 'Irene in Time', 'Casandra Malcher', 'PE', 'Khmer', 8, 133);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (15, 'Last Days, The', 'Baily Packwood', 'TH', 'New Zealand Sign Language', 18, 140);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (16, 'One Fine Day', 'Emmye Thacke', 'MX', 'Guaraní', 12, 148);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (17, 'West Side Story', 'Anstice Wannell', 'MX', 'Croatian', 13, 164);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (18, 'Gruffalo, The', 'Edik Jandel', 'MK', 'Kashmiri', 14, 120);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (19, 'Haunted World of El Superbeasto, The', 'Josephine Goodchild', 'PL', 'Tswana', 8, 164);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (20, 'Burn Paris Burn', 'Ralina Hotchkin', 'PH', 'Malagasy', 18, 127);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (21, 'Bodyguards and Assassins', 'Anna Raatz', 'CN', 'Nepali', 16, 111);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (22, 'Dante''s Inferno', 'Lyman Tippett', 'SE', 'Latvian', 10, 154);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (23, 'American Adobo', 'Robyn Houten', 'CZ', 'German', 6, 138);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (24, 'Gay Purr-ee', 'Franni Di Filippo', 'SD', 'Zulu', 17, 101);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (25, 'Stag Night', 'Xymenes Charlin', 'ID', 'Mongolian', 11, 92);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (26, 'Mondo Topless', 'Conchita Mallord', 'VE', 'Malayalam', 15, 92);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (27, 'Company, The', 'Mabelle Seeking', 'RS', 'Dzongkha', 11, 159);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (28, 'On the Threshold (Lars i porten)', 'Fallon Roadnight', 'US', 'Bosnian', 8, 167);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (29, 'So Long Letty', 'Pasquale Demschke', 'MY', 'Malay', 12, 169);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (30, 'European Vacation (aka National Lampoon''s European Vacation)', 'Nathanael Bortolini', 'CN', 'Tswana', 14, 119);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (31, 'Cosmic Journey', 'Udell Straughan', 'FR', 'Dari', 11, 138);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (32, 'That Certain Woman', 'Susi Muncaster', 'HR', 'Tajik', 12, 94);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (33, 'Jekyll + Hyde', 'Rodolfo Elldred', 'VE', 'Luxembourgish', 15, 178);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (34, 'Sun Also Rises, The', 'Veronique Dilon', 'US', 'Polish', 7, 155);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (35, 'Lost in Siberia (Ausgerechnet Sibirien)', 'Willy Ochterlony', 'CN', 'Tetum', 18, 139);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (36, 'Psychosis', 'Fanni Whooley', 'ID', 'Indonesian', 7, 163);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (37, 'Make Like a Thief (Juokse kuin varas)', 'Rene Drysdall', 'ID', 'Macedonian', 10, 167);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (38, 'Real Steel', 'Deana Lawles', 'NO', 'Filipino', 11, 109);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (39, '7 Seconds', 'Violetta Josham', 'CN', 'Telugu', 15, 96);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (40, 'Courier', 'Christoph Carthew', 'PE', 'Thai', 14, 179);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (41, 'Marooned in Iraq (Gomgashtei dar Aragh)', 'Monty Bordessa', 'CO', 'Kurdish', 14, 84);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (42, 'Assembly (Ji jie hao) ', 'Matteo Champ', 'CO', 'Maltese', 18, 103);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (43, 'Heaven Knows, Mr. Allison', 'Desiree Scallon', 'SE', 'Hiri Motu', 13, 100);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (44, 'Blue Juice', 'York Beernt', 'CN', 'Gagauz', 15, 80);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (45, 'Kolya (Kolja)', 'Barbe Hews', 'PH', 'Kashmiri', 14, 118);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (46, 'Best Seller', 'Friedrick Amber', 'ID', 'Norwegian', 12, 104);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (47, 'Pay It Forward', 'Aleda Gouldie', 'ID', 'Albanian', 18, 152);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (48, 'Humboldt County', 'Haywood Saipy', 'RU', 'Georgian', 18, 128);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (49, 'Sheepman, The', 'Lemmy Draper', 'KG', 'Kazakh', 9, 150);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (50, '47 Samurai (Chûshingura) (Loyal 47 Ronin, The)', 'Kiah Goodinge', 'CM', 'Mongolian', 13, 161);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (51, 'Blazing Saddles', 'Kendre Prescott', 'PH', 'Hiri Motu', 12, 109);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (52, 'Venom', 'Edgar Pawden', 'NL', 'Telugu', 17, 96);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (53, 'Batman Forever', 'Cate Balle', 'GR', 'Greek', 9, 103);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (54, 'Fudoh: The New Generation (Gokudô sengokushi: Fudô)', 'Sharyl Balharry', 'CA', 'Māori', 13, 101);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (55, 'Happy Gilmore', 'Rod Hartnell', 'TH', 'Sotho', 6, 111);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (56, 'Monte Carlo', 'Lynna Dominique', 'PT', 'Moldovan', 18, 140);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (57, 'Songs From the Second Floor (Sånger från andra våningen)', 'Ranice Gunn', 'BR', 'Tswana', 6, 164);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (58, 'Five Angles on Murder', 'Hugibert Espinosa', 'EC', 'Māori', 17, 119);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (59, 'Golden Child, The', 'Clemmie Whopples', 'BD', 'Portuguese', 10, 100);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (60, 'Beautiful Person, The (La belle personne)', 'Miller Issacof', 'FR', 'Latvian', 18, 86);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (61, 'Last Life in the Universe (Ruang rak noi nid mahasan)', 'Crin Fensome', 'CI', 'Lao', 7, 128);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (62, 'Tribute', 'Charita Boote', 'PH', 'Papiamento', 18, 118);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (63, 'Last Time I Saw Paris, The', 'Agnella Beevis', 'KZ', 'Montenegrin', 18, 140);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (64, 'Sky Fighters (Les Chevaliers Du Ciel)', 'Don Lebbern', 'CZ', 'Afrikaans', 17, 114);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (65, 'Killing Words (Palabras encadenadas)', 'Kain Farahar', 'CN', 'Dutch', 9, 167);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (66, 'Raiders of the Lost Ark: The Adaptation', 'Harold Oloshkin', 'CO', 'Kyrgyz', 12, 111);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (67, 'High Noon', 'Violet Stormouth', 'CN', 'Telugu', 10, 106);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (68, 'Murder of Crows, A', 'Donall Stag', 'CN', 'Tetum', 6, 136);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (69, 'Hollywood Knights, The', 'Sosanna Spurden', 'MX', 'Italian', 7, 172);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (70, 'Bounty, The', 'Augustina Esplin', 'VN', 'Thai', 6, 115);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (71, 'Six by Sondheim', 'Beryl Cruickshank', 'RU', 'Nepali', 13, 155);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (72, 'Rio Sex Comedy', 'Kalila Wrigglesworth', 'GT', 'Kyrgyz', 6, 172);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (73, 'The Elephant Man', 'Merilyn Beri', 'MU', 'Albanian', 13, 105);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (74, 'Région centrale, La', 'Any Bullivent', 'ID', 'Telugu', 7, 126);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (75, 'Reluctant Dragon, The', 'Rahal Ribbens', 'MG', 'Kurdish', 15, 166);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (76, 'Mystery (Fu cheng mi shi)', 'Calv Dirand', 'PH', 'Chinese', 7, 86);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (77, 'Orderly or Disorderly (Be Tartib ya Bedoun-e Tartib)', 'Sorcha Ardley', 'JP', 'Macedonian', 15, 124);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (78, 'Fried Green Tomatoes', 'Staford Duberry', 'PH', 'Portuguese', 16, 123);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (79, 'Ran', 'Marshall Cosley', 'TH', 'Bengali', 11, 110);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (80, 'Superman Unbound', 'Calla Pleasaunce', 'PH', 'Tetum', 9, 157);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (81, 'That Man from Rio', 'Brant Carbery', 'TG', 'Ndebele', 14, 179);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (82, 'Linsanity', 'Sinclare Girtin', 'KZ', 'Polish', 17, 106);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (83, 'My Man Godfrey', 'Dinnie Turn', 'FR', 'Lao', 10, 140);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (84, 'Boiling Point', 'Hymie Davidov', 'VE', 'Norwegian', 17, 148);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (85, 'Cloud 9', 'Marta Colcutt', 'CN', 'Lithuanian', 12, 142);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (86, 'Jerusalema (Gangster''s Paradise: Jerusalema)', 'Hyacintha Vowells', 'SI', 'Northern Sotho', 16, 94);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (87, 'Ghajini', 'Maddy Dymock', 'SO', 'Oriya', 6, 109);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (88, 'Camp Hell', 'Halimeda McGaugey', 'EE', 'Azeri', 14, 144);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (89, 'Last Unicorn, The', 'Way Watterson', 'BW', 'Aymara', 16, 97);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (90, 'Lake City', 'Giulietta Lawes', 'TH', 'Quechua', 6, 116);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (91, 'Kid Millions', 'Winonah Howlings', 'SI', 'Nepali', 9, 179);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (92, 'Creation of the Humanoids, The', 'Joelynn Beddo', 'FR', 'Armenian', 10, 174);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (93, 'Savage Messiah', 'Shina Storrock', 'NO', 'Kyrgyz', 11, 148);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (94, 'Red Army', 'Fayre Jeenes', 'PH', 'Bislama', 7, 166);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (95, 'Samson and Delilah', 'Kaylyn McLennan', 'VN', 'Somali', 6, 153);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (96, 'Now You Know', 'Reynolds Saket', 'CN', 'Marathi', 7, 126);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (97, 'Apache', 'Sasha Edinburough', 'SE', 'Bengali', 12, 83);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (98, 'Nostalghia', 'Vickie Dacca', 'NG', 'German', 17, 132);
insert into film (film_id, title, director, country, film_language, age_rating, duration) values (99, 'Intimate Relations', 'Bordy Flude', 'PT', 'Dzongkha', 9, 166);